# Generated by Django 5.0.14 on 2026-01-08 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата удаления"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, default="", verbose_name="Описание")),
                (
                    "code",
                    models.CharField(
                        help_text="Уникальный код проекта, например: PRJ-001",
                        max_length=20,
                        unique=True,
                        verbose_name="Код проекта",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("planning", "Планирование"),
                            ("in_progress", "В работе"),
                            ("review", "На проверке"),
                            ("completed", "Завершён"),
                            ("on_hold", "На паузе"),
                            ("cancelled", "Отменён"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("medium", "Средний"),
                            ("high", "Высокий"),
                            ("critical", "Критический"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        choices=[("rnd", "R&D"), ("it_projects", "IT-проекты")],
                        db_index=True,
                        max_length=20,
                        verbose_name="Подразделение",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="Дата начала")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата окончания"),
                ),
                (
                    "progress",
                    models.PositiveIntegerField(
                        default=0, help_text="0-100", verbose_name="Прогресс (%)"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Бюджет",
                    ),
                ),
                (
                    "spent",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Потрачено"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано пользователем",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Руководитель проекта",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Участники",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Изменено пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(max_length=50, verbose_name="Действие")),
                ("details", models.JSONField(default=dict, verbose_name="Детали")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "История проекта",
                "verbose_name_plural": "История проектов",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMilestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, default="", verbose_name="Описание")),
                ("due_date", models.DateField(verbose_name="Срок")),
                ("completed", models.BooleanField(default=False, verbose_name="Выполнено")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата выполнения"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Веха",
                "verbose_name_plural": "Вехи",
                "ordering": ["order", "due_date"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status", "division"], name="projects_pr_status_f37f75_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["manager", "status"], name="projects_pr_manager_9c148a_idx"),
        ),
    ]
