# Generated by Django 5.0.14 on 2026-01-09 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Research",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата удаления"),
                ),
                (
                    "created_by_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID пользователя из users_db",
                        null=True,
                        verbose_name="ID создателя",
                    ),
                ),
                (
                    "updated_by_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID пользователя из users_db",
                        null=True,
                        verbose_name="ID редактора",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, default="", verbose_name="Описание")),
                (
                    "objectives",
                    models.TextField(blank=True, default="", verbose_name="Цели исследования"),
                ),
                (
                    "methodology",
                    models.TextField(blank=True, default="", verbose_name="Методология"),
                ),
                (
                    "research_type",
                    models.CharField(
                        choices=[
                            ("market", "Маркетинговое"),
                            ("technical", "Техническое"),
                            ("competitive", "Конкурентный анализ"),
                            ("user", "Пользовательское"),
                            ("feasibility", "Анализ осуществимости"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Тип исследования",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("in_progress", "В процессе"),
                            ("submitted", "На проверке"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                            ("archived", "В архиве"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Низкий"), ("medium", "Средний"), ("high", "Высокий")],
                        default="medium",
                        max_length=10,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("public", "Публичное (все сотрудники)"),
                            ("division", "Подразделение"),
                            ("restricted", "Ограниченный доступ"),
                            ("private", "Приватное"),
                        ],
                        default="division",
                        max_length=20,
                        verbose_name="Уровень доступа",
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        choices=[("rnd", "R&D"), ("it_projects", "IT-проекты")],
                        db_index=True,
                        default="rnd",
                        max_length=20,
                        verbose_name="Подразделение",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="Дата начала")),
                ("due_date", models.DateField(blank=True, null=True, verbose_name="Срок сдачи")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата завершения"),
                ),
                (
                    "findings",
                    models.TextField(blank=True, default="", verbose_name="Результаты/Выводы"),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, default="", verbose_name="Рекомендации"),
                ),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="Теги")),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_researches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "contributors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="contributed_researches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Соавторы",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="researches",
                        to="projects.project",
                        verbose_name="Связанный проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Исследование",
                "verbose_name_plural": "Исследования",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "can_edit",
                    models.BooleanField(default=False, verbose_name="Может редактировать"),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата выдачи")),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_research_access",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кем выдан",
                    ),
                ),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_grants",
                        to="research.research",
                        verbose_name="Исследование",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_access",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступ к исследованию",
                "verbose_name_plural": "Доступы к исследованиям",
            },
        ),
        migrations.CreateModel(
            name="ResearchAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="research_attachments/%Y/%m/", verbose_name="Файл"),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="Имя файла")),
                ("file_size", models.PositiveIntegerField(default=0, verbose_name="Размер файла")),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="MIME-тип"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата загрузки"),
                ),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="research.research",
                        verbose_name="Исследование",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загружено",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вложение исследования",
                "verbose_name_plural": "Вложения исследований",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Изменено")),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="research.research",
                        verbose_name="Исследование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к исследованию",
                "verbose_name_plural": "Комментарии к исследованиям",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(max_length=50, verbose_name="Действие")),
                ("details", models.JSONField(default=dict, verbose_name="Детали")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата")),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="research.research",
                        verbose_name="Исследование",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "История исследования",
                "verbose_name_plural": "История исследований",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="research",
            index=models.Index(fields=["status", "division"], name="research_re_status_367371_idx"),
        ),
        migrations.AddIndex(
            model_name="research",
            index=models.Index(fields=["author", "status"], name="research_re_author__505545_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="researchaccess",
            unique_together={("research", "user")},
        ),
    ]
