# Generated by Django 5.0.14 on 2026-01-08 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "enabled_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Пустой список = все включены",
                        verbose_name="Включённые типы",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=True, verbose_name="Email уведомления"),
                ),
                (
                    "push_enabled",
                    models.BooleanField(default=True, verbose_name="Push уведомления"),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(default=False, verbose_name="Тихий режим"),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(blank=True, null=True, verbose_name="Начало тихого режима"),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(blank=True, null=True, verbose_name="Конец тихого режима"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки уведомлений",
                "verbose_name_plural": "Настройки уведомлений",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("task_assigned", "Назначена задача"),
                            ("task_submitted", "Задача отправлена на проверку"),
                            ("task_approved", "Задача одобрена"),
                            ("task_rejected", "Задача отклонена"),
                            ("task_deadline", "Приближается срок задачи"),
                            ("task_overdue", "Задача просрочена"),
                            ("task_comment", "Новый комментарий к задаче"),
                            ("task_mention", "Вас упомянули в задаче"),
                            ("project_created", "Создан проект"),
                            ("project_updated", "Проект обновлён"),
                            ("project_status", "Изменён статус проекта"),
                            ("project_member_added", "Вы добавлены в проект"),
                            ("project_deadline", "Приближается срок проекта"),
                            ("research_submitted", "Исследование на проверке"),
                            ("research_approved", "Исследование одобрено"),
                            ("research_rejected", "Исследование отклонено"),
                            ("research_access", "Вам предоставлен доступ"),
                            ("system", "Системное уведомление"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("normal", "Обычный"),
                            ("high", "Высокий"),
                            ("urgent", "Срочный"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Приоритет",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("message", models.TextField(blank=True, default="", verbose_name="Сообщение")),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Тип связанного объекта"
                    ),
                ),
                (
                    "related_object_id",
                    models.UUIDField(blank=True, null=True, verbose_name="ID связанного объекта"),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Дополнительные данные"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(db_index=True, default=False, verbose_name="Прочитано"),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Время прочтения"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Создано"),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="notificatio_user_id_f2ad08_idx",
                    ),
                    models.Index(
                        fields=["user", "notification_type"], name="notificatio_user_id_f77590_idx"
                    ),
                ],
            },
        ),
    ]
