# Generated by Django 5.0.14 on 2026-01-09 11:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('login_failed', 'Неудачная попытка входа'), ('create', 'Создание'), ('read', 'Просмотр'), ('update', 'Изменение'), ('delete', 'Удаление'), ('export', 'Экспорт данных'), ('import', 'Импорт данных'), ('status_change', 'Изменение статуса'), ('assignment', 'Назначение'), ('approval', 'Утверждение'), ('rejection', 'Отклонение'), ('comment', 'Комментарий'), ('file_upload', 'Загрузка файла'), ('file_download', 'Скачивание файла'), ('settings_change', 'Изменение настроек'), ('permission_change', 'Изменение прав доступа')], db_index=True, max_length=50, verbose_name='Действие')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=500, verbose_name='Представление объекта')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Формат: {"field_name": {"old": "old_value", "new": "new_value"}}', verbose_name='Изменения')),
                ('request_url', models.CharField(blank=True, max_length=2000, verbose_name='URL запроса')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='HTTP метод')),
                ('success', models.BooleanField(db_index=True, default=True, verbose_name='Успешно')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог аудита',
                'verbose_name_plural': 'Логи аудита',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'user'], name='audit_logs_timesta_d733ec_idx'), models.Index(fields=['action', '-timestamp'], name='audit_logs_action_f48619_idx'), models.Index(fields=['ip_address', '-timestamp'], name='audit_logs_ip_addr_345630_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_logs_content_b0ef47_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(db_index=True, help_text='Например: tasks, projects, users', max_length=100, verbose_name='Тип экспорта')),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF'), ('json', 'JSON')], max_length=20, verbose_name='Формат')),
                ('filters', models.JSONField(default=dict, verbose_name='Примененные фильтры')),
                ('record_count', models.PositiveIntegerField(default=0, verbose_name='Количество записей')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер файла (байты)')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время экспорта')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Экспорт данных',
                'verbose_name_plural': 'Экспорты данных',
                'db_table': 'data_exports',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='data_export_user_id_290750_idx'), models.Index(fields=['export_type', '-timestamp'], name='data_export_export__058ee2_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время входа')),
                ('success', models.BooleanField(db_index=True, default=True, verbose_name='Успешный вход')),
                ('failure_reason', models.CharField(blank=True, max_length=500, verbose_name='Причина неудачи')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Ключ сессии')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История входа',
                'verbose_name_plural': 'История входов',
                'db_table': 'login_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='login_histo_user_id_9c165b_idx'), models.Index(fields=['ip_address', '-timestamp'], name='login_histo_ip_addr_998bf5_idx')],
            },
        ),
    ]
