# Generated by Django 5.0.14 on 2026-01-08 14:40

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("department_head", "Начальник Департамента"),
                            ("management_head", "Начальник Управления"),
                            ("division_head", "Начальник отдела"),
                            ("employee", "Сотрудник"),
                        ],
                        db_index=True,
                        default="employee",
                        max_length=50,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        choices=[("rnd", "Отдел R&D"), ("it_projects", "Отдел IT-проектов")],
                        db_index=True,
                        default="rnd",
                        max_length=50,
                        verbose_name="Отдел",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="Аватар"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Доступ в админку")),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата регистрации"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="Последний вход"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["role", "division"], name="accounts_us_role_a48139_idx"),
                    models.Index(fields=["division"], name="accounts_us_divisio_8db5ab_idx"),
                ],
            },
        ),
    ]
