# Generated by Django 5.0.14 on 2026-01-08 14:40

import apps.tasks.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата удаления"),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "task_type",
                    models.CharField(
                        choices=[("T1", "Секретная (Confidential)"), ("T2", "Обычная (Standard)")],
                        db_index=True,
                        default="T2",
                        max_length=10,
                        verbose_name="Тип задачи",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В работе"),
                            ("under_division_review", "На проверке (Нач. отдела)"),
                            ("under_management_review", "На рассмотрении (Нач. Управления)"),
                            ("rework", "На доработке"),
                            ("rework_withdrawn", "На доработке (отозвано)"),
                            ("accepted", "Принято (Закрыто)"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("medium", "Средний"),
                            ("high", "Высокий"),
                            ("urgent", "Срочный"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("standard", "Обычные задачи"),
                            ("external_org", "Внешняя организация"),
                            ("external_branch", "Внешний филиал"),
                            ("external_management", "Внешнее руководство"),
                        ],
                        default="standard",
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        choices=[("rnd", "Отдел R&D"), ("it_projects", "Отдел IT-проектов")],
                        db_index=True,
                        max_length=50,
                        verbose_name="Отдел",
                    ),
                ),
                ("deadline", models.DateField(db_index=True, verbose_name="Дедлайн")),
                (
                    "approval_route",
                    models.CharField(
                        choices=[
                            ("management_only", "Только Начальник Управления (T1)"),
                            ("division_then_management", "Отдел → Управление (T2)"),
                            ("custom", "Кастомный маршрут"),
                        ],
                        default="division_then_management",
                        max_length=50,
                        verbose_name="Маршрут приемки",
                    ),
                ),
                (
                    "is_self_assigned",
                    models.BooleanField(default=False, verbose_name="Самопостановка"),
                ),
                (
                    "current_result_version",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Номер текущей версии результата"
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "co_assignees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="co_assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Соисполнители",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано пользователем",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
                (
                    "custom_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_approval_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кастомный принимающий",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Изменено пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "is_return_reason",
                    models.BooleanField(default=False, verbose_name="Причина возврата"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "mentions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mentioned_in_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Упоминания",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tasks.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("action", models.CharField(max_length=100, verbose_name="Действие")),
                ("details", models.TextField(blank=True, verbose_name="Детали")),
                (
                    "field_changes",
                    models.JSONField(blank=True, default=dict, verbose_name="Изменения полей"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="tasks.task",
                        verbose_name="Задача",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_history_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись истории",
                "verbose_name_plural": "История изменений",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskResultVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("version", models.PositiveIntegerField(verbose_name="Номер версии")),
                ("result_description", models.TextField(verbose_name="Описание результата")),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Когда отправлено"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("current", "Текущая"),
                            ("withdrawn", "Отозвана"),
                            ("rejected", "Отклонена"),
                        ],
                        default="current",
                        max_length=20,
                        verbose_name="Статус версии",
                    ),
                ),
                ("withdraw_reason", models.TextField(blank=True, verbose_name="Причина отзыва")),
                ("rejection_reason", models.TextField(blank=True, verbose_name="Причина возврата")),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто отправил",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_versions",
                        to="tasks.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия результата",
                "verbose_name_plural": "Версии результатов",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("name", models.CharField(max_length=255, verbose_name="Имя файла")),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.tasks.models.task_attachment_path, verbose_name="Файл"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(blank=True, max_length=100, verbose_name="MIME тип"),
                ),
                ("file_size", models.PositiveIntegerField(default=0, verbose_name="Размер (байт)")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tasks.task",
                        verbose_name="Задача",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
                (
                    "result_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="tasks.taskresultversion",
                        verbose_name="Версия результата",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вложение",
                "verbose_name_plural": "Вложения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status", "deadline"], name="tasks_task_status_e8ffa7_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["assignee", "status"], name="tasks_task_assigne_7928f6_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["division", "status"], name="tasks_task_divisio_22e4de_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["task_type", "status"], name="tasks_task_task_ty_265be9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskresultversion",
            unique_together={("task", "version")},
        ),
    ]
