# Generated by Django 5.0.14 on 2026-01-09 11:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_remove_project_projects_pr_manager_9c148a_idx_and_more'),
        ('tasks', '0002_remove_task_created_by_id_remove_task_updated_by_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPackage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название пакета')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('recipient', models.CharField(help_text='Внешний департамент или организация', max_length=255, verbose_name='Адресат')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sed', 'СЭД'), ('courier', 'Курьер'), ('other', 'Другое')], default='email', max_length=20, verbose_name='Канал отправки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('awaiting', 'Ожидание ответа'), ('received', 'Результат получен'), ('escalated', 'Эскалация')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('division', models.CharField(choices=[('rnd', 'R&D'), ('it_projects', 'IT-проекты')], db_index=True, max_length=20, verbose_name='Подразделение')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('expected_response_date', models.DateField(blank=True, null=True, verbose_name='Ожидаемая дата ответа')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата получения ответа')),
                ('escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата эскалации')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('linked_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_packages', to='projects.project', verbose_name='Связанный проект')),
                ('linked_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_packages', to='tasks.task', verbose_name='Связанная задача')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_packages', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Редактор')),
            ],
            options={
                'verbose_name': 'Внешний пакет',
                'verbose_name_plural': 'Внешние пакеты',
                'db_table': 'external_packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='Например: created, sent, received, escalated', max_length=50, verbose_name='Действие')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='external_packages.externalpackage', verbose_name='Пакет')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись журнала пакета',
                'verbose_name_plural': 'Записи журнала пакетов',
                'db_table': 'package_log_entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='externalpackage',
            index=models.Index(fields=['status', '-created_at'], name='external_pa_status_a36cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='externalpackage',
            index=models.Index(fields=['division', 'status'], name='external_pa_divisio_ffed8f_idx'),
        ),
        migrations.AddIndex(
            model_name='externalpackage',
            index=models.Index(fields=['responsible', 'status'], name='external_pa_respons_29e283_idx'),
        ),
    ]
